// Generated by gencpp from file custom_messages/Prueba.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_PRUEBA_H
#define CUSTOM_MESSAGES_MESSAGE_PRUEBA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_messages
{
template <class ContainerAllocator>
struct Prueba_
{
  typedef Prueba_<ContainerAllocator> Type;

  Prueba_()
    : numero_prueba(0)  {
    }
  Prueba_(const ContainerAllocator& _alloc)
    : numero_prueba(0)  {
  (void)_alloc;
    }



   typedef int32_t _numero_prueba_type;
  _numero_prueba_type numero_prueba;





  typedef boost::shared_ptr< ::custom_messages::Prueba_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::Prueba_<ContainerAllocator> const> ConstPtr;

}; // struct Prueba_

typedef ::custom_messages::Prueba_<std::allocator<void> > Prueba;

typedef boost::shared_ptr< ::custom_messages::Prueba > PruebaPtr;
typedef boost::shared_ptr< ::custom_messages::Prueba const> PruebaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::Prueba_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::Prueba_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_messages': ['/home/borjartime/rosjava_ws/src/custom_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::Prueba_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::Prueba_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::Prueba_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::Prueba_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::Prueba_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::Prueba_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::Prueba_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d1d253d7f30569507dbcd46fe13058c";
  }

  static const char* value(const ::custom_messages::Prueba_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d1d253d7f305695ULL;
  static const uint64_t static_value2 = 0x07dbcd46fe13058cULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::Prueba_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/Prueba";
  }

  static const char* value(const ::custom_messages::Prueba_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::Prueba_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 numero_prueba\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::custom_messages::Prueba_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::Prueba_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numero_prueba);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Prueba_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::Prueba_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::Prueba_<ContainerAllocator>& v)
  {
    s << indent << "numero_prueba: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numero_prueba);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_PRUEBA_H
