// Generated by gencpp from file custom_messages/TransportPrivateState.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_TRANSPORTPRIVATESTATE_H
#define CUSTOM_MESSAGES_MESSAGE_TRANSPORTPRIVATESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_messages
{
template <class ContainerAllocator>
struct TransportPrivateState_
{
  typedef TransportPrivateState_<ContainerAllocator> Type;

  TransportPrivateState_()
    : transport_state()
    , transport_docked(false)  {
    }
  TransportPrivateState_(const ContainerAllocator& _alloc)
    : transport_state(_alloc)
    , transport_docked(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _transport_state_type;
  _transport_state_type transport_state;

   typedef uint8_t _transport_docked_type;
  _transport_docked_type transport_docked;





  typedef boost::shared_ptr< ::custom_messages::TransportPrivateState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::TransportPrivateState_<ContainerAllocator> const> ConstPtr;

}; // struct TransportPrivateState_

typedef ::custom_messages::TransportPrivateState_<std::allocator<void> > TransportPrivateState;

typedef boost::shared_ptr< ::custom_messages::TransportPrivateState > TransportPrivateStatePtr;
typedef boost::shared_ptr< ::custom_messages::TransportPrivateState const> TransportPrivateStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::TransportPrivateState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::TransportPrivateState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_messages': ['/home/borjartime/rosjava_ws/src/custom_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::TransportPrivateState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::TransportPrivateState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::TransportPrivateState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::TransportPrivateState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::TransportPrivateState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::TransportPrivateState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::TransportPrivateState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "670f3bb83518dec928ea7b995f722845";
  }

  static const char* value(const ::custom_messages::TransportPrivateState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x670f3bb83518dec9ULL;
  static const uint64_t static_value2 = 0x28ea7b995f722845ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::TransportPrivateState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/TransportPrivateState";
  }

  static const char* value(const ::custom_messages::TransportPrivateState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::TransportPrivateState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string transport_state\n\
bool transport_docked\n\
";
  }

  static const char* value(const ::custom_messages::TransportPrivateState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::TransportPrivateState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transport_state);
      stream.next(m.transport_docked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransportPrivateState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::TransportPrivateState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::TransportPrivateState_<ContainerAllocator>& v)
  {
    s << indent << "transport_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.transport_state);
    s << indent << "transport_docked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.transport_docked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_TRANSPORTPRIVATESTATE_H
