// Generated by gencpp from file turtlebot_transport_flexmansys/KobukiPosition.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_KOBUKIPOSITION_H
#define TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_KOBUKIPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_transport_flexmansys
{
template <class ContainerAllocator>
struct KobukiPosition_
{
  typedef KobukiPosition_<ContainerAllocator> Type;

  KobukiPosition_()
    : transport_in_dock(false)
    , recovery_point()
    , odom_x(0.0)
    , odom_y(0.0)
    , rotation(0.0)  {
    }
  KobukiPosition_(const ContainerAllocator& _alloc)
    : transport_in_dock(false)
    , recovery_point(_alloc)
    , odom_x(0.0)
    , odom_y(0.0)
    , rotation(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _transport_in_dock_type;
  _transport_in_dock_type transport_in_dock;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _recovery_point_type;
  _recovery_point_type recovery_point;

   typedef double _odom_x_type;
  _odom_x_type odom_x;

   typedef double _odom_y_type;
  _odom_y_type odom_y;

   typedef double _rotation_type;
  _rotation_type rotation;





  typedef boost::shared_ptr< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> const> ConstPtr;

}; // struct KobukiPosition_

typedef ::turtlebot_transport_flexmansys::KobukiPosition_<std::allocator<void> > KobukiPosition;

typedef boost::shared_ptr< ::turtlebot_transport_flexmansys::KobukiPosition > KobukiPositionPtr;
typedef boost::shared_ptr< ::turtlebot_transport_flexmansys::KobukiPosition const> KobukiPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot_transport_flexmansys

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'turtlebot_transport_flexmansys': ['/home/borjartime/rosjava_ws/src/turtlebot_transport_flexmansys/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa959bfdcde117615672bd484119c1ee";
  }

  static const char* value(const ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa959bfdcde11761ULL;
  static const uint64_t static_value2 = 0x5672bd484119c1eeULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_transport_flexmansys/KobukiPosition";
  }

  static const char* value(const ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool transport_in_dock\n\
string recovery_point\n\
float64 odom_x\n\
float64 odom_y\n\
float64 rotation\n\
";
  }

  static const char* value(const ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transport_in_dock);
      stream.next(m.recovery_point);
      stream.next(m.odom_x);
      stream.next(m.odom_y);
      stream.next(m.rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KobukiPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_transport_flexmansys::KobukiPosition_<ContainerAllocator>& v)
  {
    s << indent << "transport_in_dock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.transport_in_dock);
    s << indent << "recovery_point: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.recovery_point);
    s << indent << "odom_x: ";
    Printer<double>::stream(s, indent + "  ", v.odom_x);
    s << indent << "odom_y: ";
    Printer<double>::stream(s, indent + "  ", v.odom_y);
    s << indent << "rotation: ";
    Printer<double>::stream(s, indent + "  ", v.rotation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_KOBUKIPOSITION_H
