# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_messages/KobukiObstacle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class KobukiObstacle(genpy.Message):
  _md5sum = "2aef80677f5e7bb119c67140618dc301"
  _type = "custom_messages/KobukiObstacle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool detected_obstacle_bumper
bool detected_obstacle_camera"""
  __slots__ = ['detected_obstacle_bumper','detected_obstacle_camera']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       detected_obstacle_bumper,detected_obstacle_camera

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KobukiObstacle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.detected_obstacle_bumper is None:
        self.detected_obstacle_bumper = False
      if self.detected_obstacle_camera is None:
        self.detected_obstacle_camera = False
    else:
      self.detected_obstacle_bumper = False
      self.detected_obstacle_camera = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.detected_obstacle_bumper, _x.detected_obstacle_camera))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.detected_obstacle_bumper, _x.detected_obstacle_camera,) = _get_struct_2B().unpack(str[start:end])
      self.detected_obstacle_bumper = bool(self.detected_obstacle_bumper)
      self.detected_obstacle_camera = bool(self.detected_obstacle_camera)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.detected_obstacle_bumper, _x.detected_obstacle_camera))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.detected_obstacle_bumper, _x.detected_obstacle_camera,) = _get_struct_2B().unpack(str[start:end])
      self.detected_obstacle_bumper = bool(self.detected_obstacle_bumper)
      self.detected_obstacle_camera = bool(self.detected_obstacle_camera)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
