# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtlebot_transport_flexmansys/KobukiPosition.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class KobukiPosition(genpy.Message):
  _md5sum = "fa959bfdcde117615672bd484119c1ee"
  _type = "turtlebot_transport_flexmansys/KobukiPosition"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool transport_in_dock
string recovery_point
float64 odom_x
float64 odom_y
float64 rotation"""
  __slots__ = ['transport_in_dock','recovery_point','odom_x','odom_y','rotation']
  _slot_types = ['bool','string','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       transport_in_dock,recovery_point,odom_x,odom_y,rotation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KobukiPosition, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.transport_in_dock is None:
        self.transport_in_dock = False
      if self.recovery_point is None:
        self.recovery_point = ''
      if self.odom_x is None:
        self.odom_x = 0.
      if self.odom_y is None:
        self.odom_y = 0.
      if self.rotation is None:
        self.rotation = 0.
    else:
      self.transport_in_dock = False
      self.recovery_point = ''
      self.odom_x = 0.
      self.odom_y = 0.
      self.rotation = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.transport_in_dock
      buff.write(_get_struct_B().pack(_x))
      _x = self.recovery_point
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.odom_x, _x.odom_y, _x.rotation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.transport_in_dock,) = _get_struct_B().unpack(str[start:end])
      self.transport_in_dock = bool(self.transport_in_dock)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.recovery_point = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.recovery_point = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.odom_x, _x.odom_y, _x.rotation,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.transport_in_dock
      buff.write(_get_struct_B().pack(_x))
      _x = self.recovery_point
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.odom_x, _x.odom_y, _x.rotation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.transport_in_dock,) = _get_struct_B().unpack(str[start:end])
      self.transport_in_dock = bool(self.transport_in_dock)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.recovery_point = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.recovery_point = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.odom_x, _x.odom_y, _x.rotation,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
