// Generated by gencpp from file turtlebot_transport_flexmansys/KobukiGeneral.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_KOBUKIGENERAL_H
#define TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_KOBUKIGENERAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_transport_flexmansys
{
template <class ContainerAllocator>
struct KobukiGeneral_
{
  typedef KobukiGeneral_<ContainerAllocator> Type;

  KobukiGeneral_()
    : transport_unit_name()
    , transport_unit_state()
    , battery(0.0)  {
    }
  KobukiGeneral_(const ContainerAllocator& _alloc)
    : transport_unit_name(_alloc)
    , transport_unit_state(_alloc)
    , battery(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _transport_unit_name_type;
  _transport_unit_name_type transport_unit_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _transport_unit_state_type;
  _transport_unit_state_type transport_unit_state;

   typedef float _battery_type;
  _battery_type battery;





  typedef boost::shared_ptr< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> const> ConstPtr;

}; // struct KobukiGeneral_

typedef ::turtlebot_transport_flexmansys::KobukiGeneral_<std::allocator<void> > KobukiGeneral;

typedef boost::shared_ptr< ::turtlebot_transport_flexmansys::KobukiGeneral > KobukiGeneralPtr;
typedef boost::shared_ptr< ::turtlebot_transport_flexmansys::KobukiGeneral const> KobukiGeneralConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot_transport_flexmansys

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'turtlebot_transport_flexmansys': ['/home/borjartime/catkin_ws/src/turtlebot_transport_flexmansys/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd826a4a104ac611941e72978f2a882c";
  }

  static const char* value(const ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd826a4a104ac611ULL;
  static const uint64_t static_value2 = 0x941e72978f2a882cULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_transport_flexmansys/KobukiGeneral";
  }

  static const char* value(const ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string transport_unit_name\n\
string transport_unit_state\n\
float32 battery\n\
";
  }

  static const char* value(const ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transport_unit_name);
      stream.next(m.transport_unit_state);
      stream.next(m.battery);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KobukiGeneral_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_transport_flexmansys::KobukiGeneral_<ContainerAllocator>& v)
  {
    s << indent << "transport_unit_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.transport_unit_name);
    s << indent << "transport_unit_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.transport_unit_state);
    s << indent << "battery: ";
    Printer<float>::stream(s, indent + "  ", v.battery);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_KOBUKIGENERAL_H
