// Generated by gencpp from file turtlebot_transport_flexmansys/TransportServiceMessage.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_TRANSPORTSERVICEMESSAGE_H
#define TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_TRANSPORTSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <turtlebot_transport_flexmansys/TransportServiceMessageRequest.h>
#include <turtlebot_transport_flexmansys/TransportServiceMessageResponse.h>


namespace turtlebot_transport_flexmansys
{

struct TransportServiceMessage
{

typedef TransportServiceMessageRequest Request;
typedef TransportServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransportServiceMessage
} // namespace turtlebot_transport_flexmansys


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessage > {
  static const char* value()
  {
    return "8ddb36dd3d52323557949d25fae2e281";
  }

  static const char* value(const ::turtlebot_transport_flexmansys::TransportServiceMessage&) { return value(); }
};

template<>
struct DataType< ::turtlebot_transport_flexmansys::TransportServiceMessage > {
  static const char* value()
  {
    return "turtlebot_transport_flexmansys/TransportServiceMessage";
  }

  static const char* value(const ::turtlebot_transport_flexmansys::TransportServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessageRequest> should match 
// service_traits::MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessage > 
template<>
struct MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessage >::value();
  }
  static const char* value(const ::turtlebot_transport_flexmansys::TransportServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_transport_flexmansys::TransportServiceMessageRequest> should match 
// service_traits::DataType< ::turtlebot_transport_flexmansys::TransportServiceMessage > 
template<>
struct DataType< ::turtlebot_transport_flexmansys::TransportServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_transport_flexmansys::TransportServiceMessage >::value();
  }
  static const char* value(const ::turtlebot_transport_flexmansys::TransportServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessageResponse> should match 
// service_traits::MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessage > 
template<>
struct MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_transport_flexmansys::TransportServiceMessage >::value();
  }
  static const char* value(const ::turtlebot_transport_flexmansys::TransportServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_transport_flexmansys::TransportServiceMessageResponse> should match 
// service_traits::DataType< ::turtlebot_transport_flexmansys::TransportServiceMessage > 
template<>
struct DataType< ::turtlebot_transport_flexmansys::TransportServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_transport_flexmansys::TransportServiceMessage >::value();
  }
  static const char* value(const ::turtlebot_transport_flexmansys::TransportServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_TRANSPORT_FLEXMANSYS_MESSAGE_TRANSPORTSERVICEMESSAGE_H
